### PR TITLE
remove temporary std::vector in Species::CopyCtor

### PR DESCRIPTION
**Pull request by ToruNiina**
just copy attributes to avoid heap allocation.

### CODE REVIEW

**Comment by ToruNiina** [comment]
The `homebrew/science` seems to be deprecated.
https://travis-ci.org/ecell/ecell4/jobs/339305448#L1855

**Comment by kaizu** [comment]
travis-ci fails due to using the older version of Boost (1.57). Check the minimum version in CMakeLists.txt. appveyor passed on 64-bit, but not on 32-bit (I couldn't get the reason).

BTW, do we really need the 32-bit version for Windows?

**Comment by ToruNiina** [comment]
Thanks for the comment and telling me the problem.
At least MSVC says some variable won't be aligned correctly, but I couldn't get what causes this problem.
Personally I think we don't need to support old environment. But we need more discussion about that issue.

On Travis CI, how to prepare the latest version of boost?
I have one solution. Download the source codes from www.boost.org, unzip it and tell the location to CMake. It does the job when we use only the header-only parts of the library. I usually do this.
Or we can add an apt source that provides the binary of the latest boost library. But I don't know the appropriate apt source.

So I want to know exactly what do you mean by this.
> Check the minimum version in CMakeLists.txt.

I can check the boost version and change the actual type of `attributes_container_type` by using preprocessor macros. But I think it is not good because it makes the code messy and difficult to read.
I can modify the CMake script and require the specific version of Boost. It makes the code clean, but it will fail if there is no preferred version of boost. In this case, we need a way to prepare the latest boost.

Do you have any idea about this?

**Comment by kaizu** [comment]
> I can modify the CMake script and require the specific version of Boost.  It makes the code clean, but it will fail if there is no preferred version of boost.

This is what I want to say. After this correction, `ecell4` actually requires the later version of Boost, right? Even if it's not the case, it's worth to specify the minimum version required, I think.

> Download the source codes from www.boost.org, unzip it and tell the location to CMake.

Agree. Do you know the better way to do this, @kozo2?

**Comment by ToruNiina** [comment]
I found one example in Boost.hana.
https://github.com/boostorg/hana/blob/master/.travis.yml#L180-L184

**Pull request closed without merging**
